const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS';
const UPLOAD_PICTURE_FAILURE = 'UPLOAD_PICTURE_FAILURE';

export {
  UPLOAD_PICTURE,
  UPLOAD_PICTURE_SUCCESS,
  UPLOAD_PICTURE_FAILURE
};
